function CodeDefine() { 
this.def = new Array();
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:40,type:"fcn"};
this.def["main"] = {file: "ert_main_c.html",line:194,type:"fcn"};
this.def["GCU_Model_genCode_U16GND"] = {file: "GCU_Model_genCode_c.html",line:92,type:"var"};
this.def["rtDW"] = {file: "GCU_Model_genCode_c.html",line:95,type:"var"};
this.def["rtPrevZCX"] = {file: "GCU_Model_genCode_c.html",line:98,type:"var"};
this.def["rtU"] = {file: "GCU_Model_genCode_c.html",line:101,type:"var"};
this.def["rtY"] = {file: "GCU_Model_genCode_c.html",line:104,type:"var"};
this.def["rtM_"] = {file: "GCU_Model_genCode_c.html",line:107,type:"var"};
this.def["rtM"] = {file: "GCU_Model_genCode_c.html",line:108,type:"var"};
this.def["look1_iu16lu64n48_binlcse"] = {file: "GCU_Model_genCode_c.html",line:131,type:"fcn"};
this.def["Efi_setRpmLimiter"] = {file: "GCU_Model_genCode_c.html",line:204,type:"fcn"};
this.def["Efi_unsetRpmLimiter"] = {file: "GCU_Model_genCode_c.html",line:219,type:"fcn"};
this.def["AAC_ExternalValues"] = {file: "GCU_Model_genCode_c.html",line:230,type:"fcn"};
this.def["Gearmotor_release"] = {file: "GCU_Model_genCode_c.html",line:248,type:"fcn"};
this.def["Gearmotor_turnRight"] = {file: "GCU_Model_genCode_c.html",line:258,type:"fcn"};
this.def["Gearmotor_brake"] = {file: "GCU_Model_genCode_c.html",line:276,type:"fcn"};
this.def["EngineControl_Start"] = {file: "GCU_Model_genCode_c.html",line:294,type:"fcn"};
this.def["SCAN_ADCScanADC"] = {file: "GCU_Model_genCode_c.html",line:305,type:"fcn"};
this.def["NEUTRAL_STATE"] = {file: "GCU_Model_genCode_c.html",line:312,type:"fcn"};
this.def["Gearshift_getTime"] = {file: "GCU_Model_genCode_c.html",line:345,type:"fcn"};
this.def["Clutch_setValue"] = {file: "GCU_Model_genCode_c.html",line:406,type:"fcn"};
this.def["GEARSHIFT"] = {file: "GCU_Model_genCode_c.html",line:433,type:"fcn"};
this.def["checkShift"] = {file: "GCU_Model_genCode_c.html",line:738,type:"fcn"};
this.def["getAacParam"] = {file: "GCU_Model_genCode_c.html",line:802,type:"fcn"};
this.def["aacCheckShift"] = {file: "GCU_Model_genCode_c.html",line:808,type:"fcn"};
this.def["checkClutch"] = {file: "GCU_Model_genCode_c.html",line:832,type:"fcn"};
this.def["enter_atomic_MANUAL_MODES"] = {file: "GCU_Model_genCode_c.html",line:843,type:"fcn"};
this.def["ACCELERATION"] = {file: "GCU_Model_genCode_c.html",line:852,type:"fcn"};
this.def["MODES"] = {file: "GCU_Model_genCode_c.html",line:1195,type:"fcn"};
this.def["updateOutput"] = {file: "GCU_Model_genCode_c.html",line:1321,type:"fcn"};
this.def["updateData"] = {file: "GCU_Model_genCode_c.html",line:1345,type:"fcn"};
this.def["checkGear"] = {file: "GCU_Model_genCode_c.html",line:1396,type:"fcn"};
this.def["sendAccCommand"] = {file: "GCU_Model_genCode_c.html",line:1412,type:"fcn"};
this.def["sendClutchCommand"] = {file: "GCU_Model_genCode_c.html",line:1430,type:"fcn"};
this.def["sendModeCommand"] = {file: "GCU_Model_genCode_c.html",line:1454,type:"fcn"};
this.def["sendShiftCommand"] = {file: "GCU_Model_genCode_c.html",line:1472,type:"fcn"};
this.def["sendStartEngCommand"] = {file: "GCU_Model_genCode_c.html",line:1494,type:"fcn"};
this.def["updateBuffer"] = {file: "GCU_Model_genCode_c.html",line:1510,type:"fcn"};
this.def["GCU_Model_genCode_step0"] = {file: "GCU_Model_genCode_c.html",line:1531,type:"fcn"};
this.def["GCU_Model_genCode_step1"] = {file: "GCU_Model_genCode_c.html",line:1537,type:"fcn"};
this.def["GCU_Model_genCode_step2"] = {file: "GCU_Model_genCode_c.html",line:1958,type:"fcn"};
this.def["GCU_Model_genCode_step3"] = {file: "GCU_Model_genCode_c.html",line:2223,type:"fcn"};
this.def["GCU_Model_genCode_step4"] = {file: "GCU_Model_genCode_c.html",line:2372,type:"fcn"};
this.def["GCU_Model_genCode_step5"] = {file: "GCU_Model_genCode_c.html",line:2429,type:"fcn"};
this.def["GCU_Model_genCode_step6"] = {file: "GCU_Model_genCode_c.html",line:2569,type:"fcn"};
this.def["GCU_Model_genCode_initialize"] = {file: "GCU_Model_genCode_c.html",line:2611,type:"fcn"};
this.def["DW_Efi_setRpmLimiter"] = {file: "GCU_Model_genCode_h.html",line:103,type:"type"};
this.def["DW_Efi_unsetRpmLimiter"] = {file: "GCU_Model_genCode_h.html",line:108,type:"type"};
this.def["DW_AAC_ExternalValues"] = {file: "GCU_Model_genCode_h.html",line:113,type:"type"};
this.def["DW_Gearmotor_turnRight"] = {file: "GCU_Model_genCode_h.html",line:120,type:"type"};
this.def["DW_Gearmotor_brake"] = {file: "GCU_Model_genCode_h.html",line:127,type:"type"};
this.def["DW_EngineControl_Start"] = {file: "GCU_Model_genCode_h.html",line:132,type:"type"};
this.def["DW"] = {file: "GCU_Model_genCode_h.html",line:315,type:"type"};
this.def["PrevZCX"] = {file: "GCU_Model_genCode_h.html",line:325,type:"type"};
this.def["ConstP"] = {file: "GCU_Model_genCode_h.html",line:358,type:"type"};
this.def["ExtU"] = {file: "GCU_Model_genCode_h.html",line:367,type:"type"};
this.def["ExtY"] = {file: "GCU_Model_genCode_h.html",line:375,type:"type"};
this.def["eepromRequest"] = {file: "GCU_Model_genCode_types_h.html",line:43,type:"type"};
this.def["acc_params"] = {file: "GCU_Model_genCode_types_h.html",line:63,type:"type"};
this.def["acc_values"] = {file: "GCU_Model_genCode_types_h.html",line:74,type:"type"};
this.def["RT_MODEL"] = {file: "GCU_Model_genCode_types_h.html",line:79,type:"type"};
this.def["rtConstP"] = {file: "GCU_Model_genCode_data_c.html",line:26,type:"var"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:33,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:57,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:68,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:92,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:33,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:57,type:"fcn"};
this.def["rt_I32ZCFcn"] = {file: "rt_i32zcfcn_c.html",line:25,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:31,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:32,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:33,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:34,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:35,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:36,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:42,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:54,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:60,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:66,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:72,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:43,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:50,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:57,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:29,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:47,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["ZCDirection"] = {file: "zero_crossing_types_h.html",line:31,type:"type"};
this.def["ZCSigState"] = {file: "zero_crossing_types_h.html",line:34,type:"type"};
this.def["ZCEventType"] = {file: "zero_crossing_types_h.html",line:47,type:"type"};
this.def["mdlInitializeSizes"] = {file: "Eeprom_write_c.html",line:173,type:"fcn"};
this.def["mdlInitializeSampleTimes"] = {file: "Eeprom_write_c.html",line:252,type:"fcn"};
this.def["mdlSetInputPortDataType"] = {file: "Eeprom_write_c.html",line:260,type:"fcn"};
this.def["mdlSetOutputPortDataType"] = {file: "Eeprom_write_c.html",line:266,type:"fcn"};
this.def["mdlSetDefaultPortDataTypes"] = {file: "Eeprom_write_c.html",line:272,type:"fcn"};
this.def["mdlStart"] = {file: "Eeprom_write_c.html",line:286,type:"fcn"};
this.def["mdlOutputs"] = {file: "Eeprom_write_c.html",line:294,type:"fcn"};
this.def["mdlTerminate"] = {file: "Eeprom_write_c.html",line:313,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["GCU_Model_genCode_c.html"] = "../GCU_Model_genCode.c";
	this.html2Root["GCU_Model_genCode_c.html"] = "GCU_Model_genCode_c.html";
	this.html2SrcPath["GCU_Model_genCode_h.html"] = "../GCU_Model_genCode.h";
	this.html2Root["GCU_Model_genCode_h.html"] = "GCU_Model_genCode_h.html";
	this.html2SrcPath["GCU_Model_genCode_private_h.html"] = "../GCU_Model_genCode_private.h";
	this.html2Root["GCU_Model_genCode_private_h.html"] = "GCU_Model_genCode_private_h.html";
	this.html2SrcPath["GCU_Model_genCode_types_h.html"] = "../GCU_Model_genCode_types.h";
	this.html2Root["GCU_Model_genCode_types_h.html"] = "GCU_Model_genCode_types_h.html";
	this.html2SrcPath["GCU_Model_genCode_data_c.html"] = "../GCU_Model_genCode_data.c";
	this.html2Root["GCU_Model_genCode_data_c.html"] = "GCU_Model_genCode_data_c.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_i32zcfcn_c.html"] = "../rt_i32zcfcn.c";
	this.html2Root["rt_i32zcfcn_c.html"] = "rt_i32zcfcn_c.html";
	this.html2SrcPath["rt_i32zcfcn_h.html"] = "../rt_i32zcfcn.h";
	this.html2Root["rt_i32zcfcn_h.html"] = "rt_i32zcfcn_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["zero_crossing_types_h.html"] = "../zero_crossing_types.h";
	this.html2Root["zero_crossing_types_h.html"] = "zero_crossing_types_h.html";
	this.html2SrcPath["Eeprom_write_c.html"] = "../../../../Libraries/EEPROM Library/Eeprom_write.c";
	this.html2Root["Eeprom_write_c.html"] = "Eeprom_write_c.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","GCU_Model_genCode_c.html","GCU_Model_genCode_h.html","GCU_Model_genCode_private_h.html","GCU_Model_genCode_types_h.html","GCU_Model_genCode_data_c.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_i32zcfcn_c.html","rt_i32zcfcn_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","zero_crossing_types_h.html","Eeprom_write_c.html"];
