classdef timings < Simulink.IntEnumType
 enumeration
  DEFAULT_DELAY       (20)
  DEFAULT_UP_REBOUND  (15)
  DEFAULT_UP_BRAKE    (20)
  DEFAULT_UP_PUSH_1_2 (115)
  DEFAULT_UP_PUSH_2_3 (100)
  DEFAULT_UP_PUSH_3_4 (100)
  DEFAULT_UP_PUSH_4_5 (100)
 %%  down
  DEFAULT_CLUTCH      (70)
  DEFAULT_DN_PUSH     (100)
  DEFAULT_DN_BRAKE    (15)
  DEFAULT_DN_REBOUND  (20)
 %%  neutral
  DEFAULT_NT_CLUTCH_DELAY (20)
  DEFAULT_NT_REBOUND_1_N  (15)
  DEFAULT_NT_REBOUND_2_N  (15)
  DEFAULT_NT_BRAKE_1_N    (35)
  DEFAULT_NT_BRAKE_2_N    (35)
  DEFAULT_NT_PUSH_1_N     (22)
  DEFAULT_NT_PUSH_2_N     (25)
  DEFAULT_NT_CLUTCH_1_N   (300)
  DEFAULT_NT_CLUTCH_2_N   (300)
 %%   Multiple tries
  DEFAULT_DOWN_TIME_CHECK (500)
  DEFAULT_UP_TIME_CHECK   (500)
  DEFAULT_MAX_TRIES       (2)
 end    
end