#ifndef DEF_AUTOX_PARAMS
#define DEF_AUTOX_PARAMS

#define DEF_AUTOX_RAMP_START 50
#define DEF_AUTOX_RAMP_END 0
#define DEF_AUTOX_RAMP_TIME 250
#define DEF_AUTOX_RPM_LIMIT_1_2 11000
#define DEF_AUTOX_RPM_LIMIT_2_3 11000
#define DEF_AUTOX_RPM_LIMIT_3_4 11000 
#define DEF_AUTOX_RPM_LIMIT_4_5 11000

#define DEF_AUTOX_SPEED_LIMIT_1_2 46
#define DEF_AUTOX_SPEED_LIMIT_2_3 61
#define DEF_AUTOX_SPEED_LIMIT_3_4 77
#define DEF_AUTOX_SPEED_LIMIT_4_5 113

#define DEF_AUTOX_TPS_START_LIMIT 50

#define DEF_AUTOX_END_GEAR 4

 #endif  